version: "3.8"
services:
  front-envoy:
    image: envoyproxy/envoy:v1.28-latest
    network_mode: "host"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9901/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
